CREATE TABLE IF NOT EXISTS statistics (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app         varchar(70) NOT NULL,
    uri         varchar(255) NOT NULL,
    ip          varchar(16) NOT NULL,
    timestamp   TIMESTAMP NOT NULL
);